-- METRIC 1: SELLER SCORECARD

-- METRIC 2: TOP AND BOTTOM 5 SELLERS BY GMV

-- METRIC 3: CATEGORY VELOCITY - FAST/SLOW MOVING

-- METRIC 4: REPEAT PURCHASE RATE BY CATEGORY

--METRIC 5: NEW VS. RETURNING SELLER GMV CONTRIBUTION OVER TIME
